version: '3'

services:
  mathkvbot:
    image: aismagilov/mathkvbot
    labels:
      - "com.centurylinklabs.watchtower.scope=mathkvbot"
    restart: always
    volumes:
      - ./config.py:/usr/src/app/config.py
      - ./token.json:/usr/src/app/token.json

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --scope mathkvbot
    labels:
      - "com.centurylinklabs.watchtower.scope=mathkvbot"