name: code-checks
on:
  push:
    tags:
      - '*'
    branches: 
      - master
  pull_request:
    branches:
      - master 

jobs:
  lint-python:
    name: Lint using black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          use-black: true
          use-pylint: false
          use-pycodestyle: false
          use-flake8: false
          use-mypy: false
          use-isort: false

  build-docker:
    name: Build the Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag smallreadbot:$(date +%s)